// import { prisma } from "../script";

const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();



async function main() {

    // id         Int     @id @default(autoincrement())
    // name       String
    // mcc        String
    // isoCode    String
    // region     String
    // keywords   String?
    // pricePerGB Float


    await prisma.country.createMany({
        data: [
            { mcc: 'AFG', isoCode: 'AF', name: 'Afghanistan', region: 'Asia Pacific', pricePerGB: 6.54 },
            { mcc: 'ALA', isoCode: 'AX', name: 'Åland Islands', region: 'Europe', pricePerGB: 0.92 },
            { mcc: 'ALB', isoCode: 'AL', name: 'Albania', region: 'Europe', pricePerGB: 1.34 },
            { mcc: 'DZA', isoCode: 'DZ', name: 'Algeria', region: 'Middle East', pricePerGB: 1.08 },
            { mcc: 'ASM', isoCode: 'AS', name: 'American Samoa', region: 'Asia Pacific', pricePerGB: 68.16 },
            { mcc: 'AND', isoCode: 'AD', name: 'Andorra', region: 'Europe', pricePerGB: 3.44 },
            { mcc: 'AGO', isoCode: 'AO', name: 'Angola', region: 'Africa', pricePerGB: 13.7 },
            { mcc: 'AIA', isoCode: 'AI', name: 'Anguilla', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'ATG', isoCode: 'AG', name: 'Antigua & Barbuda', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'ARG', isoCode: 'AR', name: 'Argentina', region: 'Latin America', pricePerGB: 2.68 },
            { mcc: 'ARM', isoCode: 'AM', name: 'Armenia', region: 'Europe', pricePerGB: 1.78 },
            { mcc: 'ABW', isoCode: 'AW', name: 'Aruba', region: 'Latin America', pricePerGB: 6.49 },
            { mcc: 'AUS', isoCode: 'AU', name: 'Australia', region: 'Asia Pacific', pricePerGB: 1.12 },
            { mcc: 'AUT', isoCode: 'AT', name: 'Austria', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'AZE', isoCode: 'AZ', name: 'Azerbaijan', region: 'Asia Pacific', pricePerGB: 2.97 },
            { mcc: 'BHS', isoCode: 'BS', name: 'Bahamas', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'BHR', isoCode: 'BH', name: 'Bahrain', region: 'Middle East', pricePerGB: 2.39 },
            { mcc: 'BGD', isoCode: 'BD', name: 'Bangladesh', region: 'Asia Pacific', pricePerGB: 1.49 },
            { mcc: 'BRB', isoCode: 'BB', name: 'Barbados', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'BLR', isoCode: 'BY', name: 'Belarus', region: 'Europe', pricePerGB: 2.08 },
            { mcc: 'BEL', isoCode: 'BE', name: 'Belgium', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'BLZ', isoCode: 'BZ', name: 'Belize', region: 'Latin America', pricePerGB: 13.99 },
            { mcc: 'BEN', isoCode: 'BJ', name: 'Benin', region: 'Africa', pricePerGB: 5.6 },
            { mcc: 'BMU', isoCode: 'BM', name: 'Bermuda', region: 'Latin America', pricePerGB: 5.38 },
            { mcc: 'BTN', isoCode: 'BT', name: 'Bhutan', region: 'Asia Pacific', pricePerGB: 275.24 },
            { mcc: 'BOL', isoCode: 'BO', name: 'Bolivia', region: 'Latin America', pricePerGB: 5.05 },
            { mcc: 'BES', isoCode: 'BQ', name: 'Bonaire', region: 'Latin America', pricePerGB: 8.03 },
            { mcc: 'BIH', isoCode: 'BA', name: 'Bosnia & Herzegovina', region: 'Europe', pricePerGB: 1.15 },
            { mcc: 'BWA', isoCode: 'BW', name: 'Botswana', region: 'Africa', pricePerGB: 5.6 },
            { mcc: 'BRA', isoCode: 'BR', name: 'Brazil', region: 'Latin America', pricePerGB: 2.32 },
            { mcc: 'VGB', isoCode: 'VG', name: 'British Virgin Islands', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'BRN', isoCode: 'BN', name: 'Brunei', region: 'Asia Pacific', pricePerGB: 3.39 },
            { mcc: 'BGR', isoCode: 'BG', name: 'Bulgaria', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'BFA', isoCode: 'BF', name: 'Burkina Faso', region: 'Africa', pricePerGB: 5.6 },
            { mcc: 'BDI', isoCode: 'BI', name: 'Burundi', region: 'Africa', pricePerGB: 17.31 },
            { mcc: 'KHM', isoCode: 'KH', name: 'Cambodia', region: 'Asia Pacific', pricePerGB: 2.82 },
            { mcc: 'CMR', isoCode: 'CM', name: 'Cameroon', region: 'Africa', pricePerGB: 3.92 },
            { mcc: 'CAN', isoCode: 'CA', name: 'Canada', region: 'North America', pricePerGB: 1.97 },
            { mcc: 'CPV', isoCode: 'CV', name: 'Cape Verde', region: 'Africa', pricePerGB: 12.7 },
            { mcc: 'CYM', isoCode: 'KY', name: 'Cayman Islands', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'CAF', isoCode: 'CF', name: 'Central African Republic', region: 'Africa', pricePerGB: 5.6 },
            { mcc: 'TCD', isoCode: 'TD', name: 'Chad', region: 'Africa', pricePerGB: 3.92 },
            { mcc: 'CHL', isoCode: 'CL', name: 'Chile', region: 'Latin America', pricePerGB: 2.82 },
            { mcc: 'CHN', isoCode: 'CN', name: 'China', region: 'Asia Pacific', pricePerGB: 1.12 },
            { mcc: 'COL', isoCode: 'CO', name: 'Colombia', region: 'Latin America', pricePerGB: 2.82 },
            { mcc: 'COD', isoCode: 'CD', name: 'Congo, (DRC)', region: 'Africa', pricePerGB: 3.94 },
            { mcc: 'COG', isoCode: 'CG', name: 'Congo, Republic', region: 'Africa', pricePerGB: 3.92 },
            { mcc: 'CRI', isoCode: 'CR', name: 'Costa Rica', region: 'Latin America', pricePerGB: 1.83 },
            { mcc: 'CIV', isoCode: 'CI', name: 'Cote d’Ivoire', region: 'Africa', pricePerGB: 5.6 },
            { mcc: 'HRV', isoCode: 'HR', name: 'Croatia', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'CUB', isoCode: 'CU', name: 'Cuba', region: 'Latin America', pricePerGB: 16.99 },
            { mcc: 'CUW', isoCode: 'CW', name: 'Curacao', region: 'Latin America', pricePerGB: 8.03 },
            { mcc: 'CYP', isoCode: 'CY', name: 'Cyprus', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'CZE', isoCode: 'CZ', name: 'Czech Republic', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'DNK', isoCode: 'DK', name: 'Denmark', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'DMA', isoCode: 'DM', name: 'Dominica', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'DOM', isoCode: 'DO', name: 'Dominican Republic', region: 'Latin America', pricePerGB: 1.41 },
            { mcc: 'ECU', isoCode: 'EC', name: 'Ecuador', region: 'Latin America', pricePerGB: 1.41 },
            { mcc: 'EGY', isoCode: 'EG', name: 'Egypt', region: 'Middle East', pricePerGB: 1.48 },
            { mcc: 'SLV', isoCode: 'SV', name: 'El Salvador', region: 'Latin America', pricePerGB: 1.41 },
            { mcc: 'GNQ', isoCode: 'GQ', name: 'Equatorial Guinea', region: 'Africa', pricePerGB: 122.18 },
            { mcc: 'EST', isoCode: 'EE', name: 'Estonia', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'SWZ', isoCode: 'SZ', name: 'Eswatini', region: 'Africa', pricePerGB: 7.07 },
            { mcc: 'ETH', isoCode: 'ET', name: 'Ethiopia', region: 'Africa', pricePerGB: 7.5 },
            { mcc: 'FRO', isoCode: 'FO', name: 'Faroe Islands', region: 'Europe', pricePerGB: 1.87 },
            { mcc: 'FJI', isoCode: 'FJ', name: 'Fiji', region: 'Asia Pacific', pricePerGB: 7.66 },
            { mcc: 'FIN', isoCode: 'FI', name: 'Finland', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'FRA', isoCode: 'FR', name: 'France', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'GUF', isoCode: 'GF', name: 'French Guiana', region: 'Latin America', pricePerGB: 0.85 },
            { mcc: 'PYF', isoCode: 'PF', name: 'French Polynesia', region: 'Asia Pacific', pricePerGB: 18.67 },
            { mcc: 'GAB', isoCode: 'GA', name: 'Gabon', region: 'Africa', pricePerGB: 3.94 },
            { mcc: 'GMB', isoCode: 'GM', name: 'Gambia', region: 'Africa', pricePerGB: 8.59 },
            { mcc: 'GEO', isoCode: 'GE', name: 'Georgia', region: 'Europe', pricePerGB: 1.15 },
            { mcc: 'DEU', isoCode: 'DE', name: 'Germany', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'GHA', isoCode: 'GH', name: 'Ghana', region: 'Africa', pricePerGB: 3.12 },
            { mcc: 'GIB', isoCode: 'GI', name: 'Gibraltar', region: 'Europe', pricePerGB: 0.85 },
            { mcc: 'GRC', isoCode: 'GR', name: 'Greece', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'GRL', isoCode: 'GL', name: 'Greenland', region: 'Europe', pricePerGB: 5.6 },
            { mcc: 'GRD', isoCode: 'GD', name: 'Grenada', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'GLP', isoCode: 'GP', name: 'Guadeloupe', region: 'Latin America', pricePerGB: 0.85 },
            { mcc: 'GUM', isoCode: 'GU', name: 'Guam', region: 'Asia Pacific', pricePerGB: 5.61 },
            { mcc: 'GTM', isoCode: 'GT', name: 'Guatemala', region: 'Latin America', pricePerGB: 1.41 },
            { mcc: 'GGY', isoCode: 'GG', name: 'Guernsey', region: 'Europe', pricePerGB: 3.46 },
            { mcc: 'GIN', isoCode: 'GN', name: 'Guinea', region: 'Africa', pricePerGB: 5.6 },
            { mcc: 'GNB', isoCode: 'GW', name: 'Guinea-Bissau', region: 'Africa', pricePerGB: 5.6 },
            { mcc: 'GUY', isoCode: 'GY', name: 'Guyana', region: 'Latin America', pricePerGB: 5.79 },
            { mcc: 'HTI', isoCode: 'HT', name: 'Haiti', region: 'Latin America', pricePerGB: 8.03 },
            { mcc: 'HND', isoCode: 'HN', name: 'Honduras', region: 'Latin America', pricePerGB: 1.41 },
            { mcc: 'HKG', isoCode: 'HK', name: 'Hong Kong', region: 'Asia Pacific', pricePerGB: 1.15 },
            { mcc: 'HUN', isoCode: 'HU', name: 'Hungary', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'ISL', isoCode: 'IS', name: 'Iceland', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'IND', isoCode: 'IN', name: 'India', region: 'Asia Pacific', pricePerGB: 1.75 },
            { mcc: 'IDN', isoCode: 'ID', name: 'Indonesia', region: 'Asia Pacific', pricePerGB: 1.04 },
            { mcc: 'IRQ', isoCode: 'IQ', name: 'Iraq', region: 'Middle East', pricePerGB: 2.39 },
            { mcc: 'IRL', isoCode: 'IE', name: 'Ireland', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'IMN', isoCode: 'IM', name: 'Isle of Man', region: 'Europe', pricePerGB: 3.35 },
            { mcc: 'ISR', isoCode: 'IL', name: 'Israel', region: 'Middle East', pricePerGB: 1.3 },
            { mcc: 'ITA', isoCode: 'IT', name: 'Italy', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'JAM', isoCode: 'JM', name: 'Jamaica', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'JPN', isoCode: 'JP', name: 'Japan', region: 'Asia Pacific', pricePerGB: 1.15 },
            { mcc: 'JEY', isoCode: 'JE', name: 'Jersey', region: 'Europe', pricePerGB: 3.46 },
            { mcc: 'JOR', isoCode: 'JO', name: 'Jordan', region: 'Middle East', pricePerGB: 2.11 },
            { mcc: 'KAZ', isoCode: 'KZ', name: 'Kazakhstan', region: 'Asia Pacific', pricePerGB: 1.15 },
            { mcc: 'KEN', isoCode: 'KE', name: 'Kenya', region: 'Africa', pricePerGB: 3.24 },
            { mcc: 'KOR', isoCode: 'KR', name: 'Korea, Republic of', region: 'Asia Pacific', pricePerGB: 0.99 },
            { mcc: 'XKX', isoCode: 'XK', name: 'Kosovo', region: 'Europe', pricePerGB: 2.24 },
            { mcc: 'KWT', isoCode: 'KW', name: 'Kuwait', region: 'Middle East', pricePerGB: 2.02 },
            { mcc: 'KGZ', isoCode: 'KG', name: 'Kyrgyzstan', region: 'Asia Pacific', pricePerGB: 1.15 },
            { mcc: 'LAO', isoCode: 'LA', name: 'Laos', region: 'Asia Pacific', pricePerGB: 3.66 },
            { mcc: 'LVA', isoCode: 'LV', name: 'Latvia', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'LBN', isoCode: 'LB', name: 'Lebanon', region: 'Middle East', pricePerGB: 46.68 },
            { mcc: 'LSO', isoCode: 'LS', name: 'Lesotho', region: 'Africa', pricePerGB: 2.31 },
            { mcc: 'LBR', isoCode: 'LR', name: 'Liberia', region: 'Africa', pricePerGB: 4.43 },
            { mcc: 'LBY', isoCode: 'LY', name: 'Libya', region: 'Africa', pricePerGB: 1153.8 },
            { mcc: 'LIE', isoCode: 'LI', name: 'Liechtenstein', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'LTU', isoCode: 'LT', name: 'Lithuania', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'LUX', isoCode: 'LU', name: 'Luxembourg', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'MAC', isoCode: 'MO', name: 'Macau', region: 'Asia Pacific', pricePerGB: 1.15 },
            { mcc: 'MKD', isoCode: 'MK', name: 'Macedonia', region: 'Europe', pricePerGB: 1.25 },
            { mcc: 'MDG', isoCode: 'MG', name: 'Madagascar', region: 'Africa', pricePerGB: 3.06 },
            { mcc: 'MWI', isoCode: 'MW', name: 'Malawi', region: 'Africa', pricePerGB: 3.94 },
            { mcc: 'MYS', isoCode: 'MY', name: 'Malaysia', region: 'Asia Pacific', pricePerGB: 0.7 },
            { mcc: 'MDV', isoCode: 'MV', name: 'Maldives', region: 'Asia Pacific', pricePerGB: 9.77 },
            { mcc: 'MLI', isoCode: 'ML', name: 'Mali', region: 'Africa', pricePerGB: 5.6 },
            { mcc: 'MLT', isoCode: 'MT', name: 'Malta', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'MTQ', isoCode: 'MQ', name: 'Martinique', region: 'Latin America', pricePerGB: 0.85 },
            { mcc: 'MRT', isoCode: 'MR', name: 'Mauritania', region: 'Africa', pricePerGB: 8.31 },
            { mcc: 'MUS', isoCode: 'MU', name: 'Mauritius', region: 'Africa', pricePerGB: 6.49 },
            { mcc: 'MYT', isoCode: 'YT', name: 'Mayotte', region: 'Africa', pricePerGB: 0.85 },
            { mcc: 'MEX', isoCode: 'MX', name: 'Mexico', region: 'Latin America', pricePerGB: 1.97 },
            { mcc: 'MDA', isoCode: 'MD', name: 'Moldova', region: 'Europe', pricePerGB: 2.46 },
            { mcc: 'MCO', isoCode: 'MC', name: 'Monaco', region: 'Europe', pricePerGB: 2.8 },
            { mcc: 'MNG', isoCode: 'MN', name: 'Mongolia', region: 'Asia Pacific', pricePerGB: 4.61 },
            { mcc: 'MNE', isoCode: 'ME', name: 'Montenegro', region: 'Europe', pricePerGB: 1.44 },
            { mcc: 'MSR', isoCode: 'MS', name: 'Montserrat', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'MAR', isoCode: 'MA', name: 'Morocco', region: 'Middle East', pricePerGB: 1.37 },
            { mcc: 'MOZ', isoCode: 'MZ', name: 'Mozambique', region: 'Africa', pricePerGB: 5.6 },
            { mcc: 'MMR', isoCode: 'MM', name: 'Myanmar', region: 'Asia Pacific', pricePerGB: 2.98 },
            { mcc: 'NAM', isoCode: 'NA', name: 'Namibia', region: 'Africa', pricePerGB: 11.17 },
            { mcc: 'NRU', isoCode: 'NR', name: 'Nauru', region: 'Asia Pacific', pricePerGB: 18.75 },
            { mcc: 'NPL', isoCode: 'NP', name: 'Nepal', region: 'Asia Pacific', pricePerGB: 2.82 },
            { mcc: 'NLD', isoCode: 'NL', name: 'Netherlands', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'ANT', isoCode: 'NA', name: 'Netherlands Antilles', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'NCL', isoCode: 'NC', name: 'New Caledonia', region: 'Asia Pacific', pricePerGB: 18.67 },
            { mcc: 'NZL', isoCode: 'NZ', name: 'New Zealand', region: 'Asia Pacific', pricePerGB: 1.13 },
            { mcc: 'NIC', isoCode: 'NI', name: 'Nicaragua', region: 'Latin America', pricePerGB: 1.41 },
            { mcc: 'NER', isoCode: 'NE', name: 'Niger', region: 'Africa', pricePerGB: 3.94 },
            { mcc: 'NGA', isoCode: 'NG', name: 'Nigeria', region: 'Africa', pricePerGB: 3.8 },
            { mcc: 'MNP', isoCode: 'MP', name: 'Northern Mariana Islands', region: 'Asia Pacific', pricePerGB: 102.51 },
            { mcc: 'NOR', isoCode: 'NO', name: 'Norway', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'OMN', isoCode: 'OM', name: 'Oman', region: 'Middle East', pricePerGB: 2.89 },
            { mcc: 'PAK', isoCode: 'PK', name: 'Pakistan', region: 'Asia Pacific', pricePerGB: 1.19 },
            { mcc: 'PSE', isoCode: 'PS', name: 'Palestine', region: 'Middle East', pricePerGB: 2.16 },
            { mcc: 'PAN', isoCode: 'PA', name: 'Panama', region: 'Latin America', pricePerGB: 1.97 },
            { mcc: 'PNG', isoCode: 'PG', name: 'Papua New Guinea', region: 'Asia Pacific', pricePerGB: 8.59 },
            { mcc: 'PRY', isoCode: 'PY', name: 'Paraguay', region: 'Latin America', pricePerGB: 1.75 },
            { mcc: 'PER', isoCode: 'PE', name: 'Peru', region: 'Latin America', pricePerGB: 1.75 },
            { mcc: 'PHL', isoCode: 'PH', name: 'Philippines', region: 'Asia Pacific', pricePerGB: 1.67 },
            { mcc: 'POL', isoCode: 'PL', name: 'Poland', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'PRT', isoCode: 'PT', name: 'Portugal', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'PRI', isoCode: 'PR', name: 'Puerto Rico', region: 'North America', pricePerGB: 1.13 },
            { mcc: 'QAT', isoCode: 'QA', name: 'Qatar', region: 'Middle East', pricePerGB: 1.55 },
            { mcc: 'REU', isoCode: 'RE', name: 'Reunion', region: 'Africa', pricePerGB: 0.85 },
            { mcc: 'ROM', isoCode: 'RO', name: 'Romania', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'RUS', isoCode: 'RU', name: 'Russia', region: 'Europe', pricePerGB: 2.47 },
            { mcc: 'RWA', isoCode: 'RW', name: 'Rwanda', region: 'Africa', pricePerGB: 3.92 },
            { mcc: 'BLM', isoCode: 'BL', name: 'Saint Barthelemy', region: 'Latin America', pricePerGB: 1.44 },
            { mcc: 'MAF', isoCode: 'MF', name: 'Saint Martin (French Part)', region: 'Latin America', pricePerGB: 1.85 },
            { mcc: 'WSM', isoCode: 'WS', name: 'Samoa', region: 'Asia Pacific', pricePerGB: 6.91 },
            { mcc: 'ITA', isoCode: 'IT', name: 'San Marino', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'STP', isoCode: 'ST', name: 'Sao Tome and Principe', region: 'Africa', pricePerGB: 24.69 },
            { mcc: 'SAU', isoCode: 'SA', name: 'Saudi Arabia', region: 'Middle East', pricePerGB: 2.24 },
            { mcc: 'SEN', isoCode: 'SN', name: 'Senegal', region: 'Africa', pricePerGB: 3.92 },
            { mcc: 'SRB', isoCode: 'RS', name: 'Serbia', region: 'Europe', pricePerGB: 1.27 },
            { mcc: 'SYC', isoCode: 'SC', name: 'Seychelles', region: 'Africa', pricePerGB: 3.94 },
            { mcc: 'SLE', isoCode: 'SL', name: 'Sierra Leone', region: 'Africa', pricePerGB: 5.16 },
            { mcc: 'SGP', isoCode: 'SG', name: 'Singapore', region: 'Asia Pacific', pricePerGB: 0.92 },
            { mcc: 'SXM', isoCode: 'SX', name: 'Sint Maarten', region: 'Latin America', pricePerGB: 12.35 },
            { mcc: 'SVK', isoCode: 'SK', name: 'Slovakia', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'SVN', isoCode: 'SI', name: 'Slovenia', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'SLB', isoCode: 'SB', name: 'Solomon Islands', region: 'Asia Pacific', pricePerGB: 59.64 },
            { mcc: 'ZAF', isoCode: 'ZA', name: 'South Africa', region: 'Africa', pricePerGB: 2.67 },
            { mcc: 'SSD', isoCode: 'SS', name: 'South Sudan', region: 'Africa', pricePerGB: 2.51 },
            { mcc: 'ESP', isoCode: 'ES', name: 'Spain', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'LKA', isoCode: 'LK', name: 'Sri Lanka', region: 'Asia Pacific', pricePerGB: 1.86 },
            { mcc: 'KNA', isoCode: 'KN', name: 'St Kitts & Nevis', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'LCA', isoCode: 'LC', name: 'St Lucia', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'VCT', isoCode: 'VC', name: 'St Vincent & the Grenadines', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'SDN', isoCode: 'SD', name: 'Sudan', region: 'Africa', pricePerGB: 9.06 },
            { mcc: 'SUR', isoCode: 'SR', name: 'Suriname', region: 'Latin America', pricePerGB: 8.03 },
            { mcc: 'SZW', isoCode: 'SZ', name: 'Swaziland', region: 'Africa', pricePerGB: 7.07 },
            { mcc: 'SWE', isoCode: 'SE', name: 'Sweden', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'CHE', isoCode: 'CH', name: 'Switzerland', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'TWN', isoCode: 'TW', name: 'Taiwan', region: 'Asia Pacific', pricePerGB: 1.13 },
            { mcc: 'TJK', isoCode: 'TJ', name: 'Tajikistan', region: 'Asia Pacific', pricePerGB: 10.56 },
            { mcc: 'TZA', isoCode: 'TZ', name: 'Tanzania', region: 'Africa', pricePerGB: 3.94 },
            { mcc: 'THA', isoCode: 'TH', name: 'Thailand', region: 'Asia Pacific', pricePerGB: 1.06 },
            { mcc: 'TLS', isoCode: 'TL', name: 'Timor L\'este', region: 'Asia Pacific', pricePerGB: 91.12 },
            { mcc: 'TGO', isoCode: 'TG', name: 'Togo', region: 'Africa', pricePerGB: 21.63 },
            { mcc: 'TON', isoCode: 'TO', name: 'Tonga', region: 'Asia Pacific', pricePerGB: 8.82 },
            { mcc: 'TTO', isoCode: 'TT', name: 'Trinidad & Tobago', region: 'Latin America', pricePerGB: 8.03 },
            { mcc: 'TUN', isoCode: 'TN', name: 'Tunisia', region: 'Middle East', pricePerGB: 1.3 },
            { mcc: 'TUR', isoCode: 'TR', name: 'Turkey', region: 'Middle East', pricePerGB: 0.58 },
            { mcc: 'TCA', isoCode: 'TC', name: 'Turks & Caicos Islands', region: 'Latin America', pricePerGB: 4.86 },
            { mcc: 'UGA', isoCode: 'UG', name: 'Uganda', region: 'Africa', pricePerGB: 3.92 },
            { mcc: 'UKR', isoCode: 'UA', name: 'Ukraine', region: 'Europe', pricePerGB: 0.7 },
            { mcc: 'ARE', isoCode: 'AE', name: 'United Arab Emirates', region: 'Middle East', pricePerGB: 2.11 },
            { mcc: 'GBR', isoCode: 'GB', name: 'United Kingdom', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'USA', isoCode: 'US', name: 'United States', region: 'North America', pricePerGB: 0.7 },
            { mcc: 'VIR', isoCode: 'VI', name: 'United States Virgin Islands', region: 'North America', pricePerGB: 1.13 },
            { mcc: 'URY', isoCode: 'UY', name: 'Uruguay', region: 'Latin America', pricePerGB: 1.75 },
            { mcc: 'UZB', isoCode: 'UZ', name: 'Uzbekistan', region: 'Asia Pacific', pricePerGB: 1.19 },
            { mcc: 'VUT', isoCode: 'VU', name: 'Vanuatu', region: 'Asia Pacific', pricePerGB: 17.31 },
            { mcc: 'ITA', isoCode: 'IT', name: 'Vatican City', region: 'EU28', pricePerGB: 0.85 },
            { mcc: 'VEN', isoCode: 'VE', name: 'Venezuela', region: 'Latin America', pricePerGB: 129.8 },
            { mcc: 'VNM', isoCode: 'VN', name: 'Vietnam', region: 'Asia Pacific', pricePerGB: 1.44 },
            { mcc: 'YEM', isoCode: 'YE', name: 'Yemen', region: 'Middle East', pricePerGB: 5.6 },
            { mcc: 'ZMB', isoCode: 'ZM', name: 'Zambia', region: 'Africa', pricePerGB: 3.94 },
            { mcc: 'ZWE', isoCode: 'ZW', name: 'Zimbabwe', region: 'Africa', pricePerGB: 42.25 },
        ],
    });


    await prisma.region.createMany({
        data: [
            { name: 'Asia Pacific', code: 'asia-pacific' },
            { name: 'Europe', code: 'europe' },
            { name: 'Middle East', code: 'middle-east' },
            { name: 'Africa', code: 'africa' },
            { name: 'Latin America', code: 'latin-america' },
            { name: 'EU28', code: 'eu28' },
            { name: 'North America', code: 'north-america' },
        ],
    });
    // await prisma.regionSupportedCountry.createMany({
    //     data: [
    //         { regionId: 'Asia Pacific', code: 'asia-pacific' },

    //     ],
    // });





}

main()
    .then(() => {
        console.log('Database seeded successfully!')
    })
    .catch((e) => {
        console.error(e)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })