// import { prisma } from "../script";


const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();



async function main() {
    // model CouponCode {
    // id           Int @id @default (autoincrement())
    // code         String @unique
    // percentage   Int
    // subjectEmail String
    // subjectName  String
    // createdAt    DateTime @default (now())

    // transactions Transaction[]
    // }


    // await prisma.review.createMany({
    //     data: [
    //         { rating: 5, showOnHome: true, name: "Marko", lastName: "Trninic", comment: "Ova aplikacija fenomelna. Svaka cast!" },
    //         { rating: 5, showOnHome: true, name: "Aleksandar", lastName: "Obradovic", comment: "Je li moguce da ovako dobro radi?" },
    //         { rating: 5, showOnHome: true, name: "Donald", lastName: "Trump", comment: "Kad god idem kod Putina kupujem ovdje net jer im je u Rusiji uzas net.." },
    //         { rating: 3, showOnHome: false, name: "Mirko", lastName: "Mirkic", comment: "Onako..." },
    //         { rating: 2, showOnHome: false, name: "Marko", lastName: "Baric", comment: "Ne radi mi nesto..." },

    //     ],
    // });



    await prisma.country.createMany({
        data: [
            { mcc: 'AFG', isoCode: 'AF', displayNameEn: 'Afghanistan', displayNameSr: 'Avganistan' },
            { mcc: 'ALA', isoCode: 'AX', displayNameEn: 'Åland Islands', displayNameSr: 'Alandska ostrva' },
            { mcc: 'ALB', isoCode: 'AL', displayNameEn: 'Albania', displayNameSr: 'Albanija' },
            { mcc: 'DZA', isoCode: 'DZ', displayNameEn: 'Algeria', displayNameSr: 'Alžir' },
            { mcc: 'ASM', isoCode: 'AS', displayNameEn: 'American Samoa', displayNameSr: 'Američka Samoa' },
            { mcc: 'AND', isoCode: 'AD', displayNameEn: 'Andorra', displayNameSr: 'Andora' },
            { mcc: 'AGO', isoCode: 'AO', displayNameEn: 'Angola', displayNameSr: 'Angola' },
            { mcc: 'AIA', isoCode: 'AI', displayNameEn: 'Anguilla', displayNameSr: 'Angvila' },
            { mcc: 'ATG', isoCode: 'AG', displayNameEn: 'Antigua & Barbuda', displayNameSr: 'Antigva i Barbuda' },
            { mcc: 'ARG', isoCode: 'AR', displayNameEn: 'Argentina', displayNameSr: 'Argentina' },
            { mcc: 'ARM', isoCode: 'AM', displayNameEn: 'Armenia', displayNameSr: 'Jermenija' },
            { mcc: 'ABW', isoCode: 'AW', displayNameEn: 'Aruba', displayNameSr: 'Aruba' },
            { mcc: 'AUS', isoCode: 'AU', displayNameEn: 'Australia', displayNameSr: 'Australija' },
            { mcc: 'AUT', isoCode: 'AT', displayNameEn: 'Austria', displayNameSr: 'Austrija' },
            { mcc: 'AZE', isoCode: 'AZ', displayNameEn: 'Azerbaijan', displayNameSr: 'Azerbejdžan' },
            { mcc: 'BHS', isoCode: 'BS', displayNameEn: 'Bahamas', displayNameSr: 'Bahami' },
            { mcc: 'BHR', isoCode: 'BH', displayNameEn: 'Bahrain', displayNameSr: 'Bahrein' },
            { mcc: 'BGD', isoCode: 'BD', displayNameEn: 'Bangladesh', displayNameSr: 'Bangladeš' },
            { mcc: 'BRB', isoCode: 'BB', displayNameEn: 'Barbados', displayNameSr: 'Barbados' },
            { mcc: 'BLR', isoCode: 'BY', displayNameEn: 'Belarus', displayNameSr: 'Bjelorusija' },
            { mcc: 'BEL', isoCode: 'BE', displayNameEn: 'Belgium', displayNameSr: 'Belgija' },
            { mcc: 'BLZ', isoCode: 'BZ', displayNameEn: 'Belize', displayNameSr: 'Belize' },
            { mcc: 'BEN', isoCode: 'BJ', displayNameEn: 'Benin', displayNameSr: 'Benin' },
            { mcc: 'BMU', isoCode: 'BM', displayNameEn: 'Bermuda', displayNameSr: 'Bermuda' },
            { mcc: 'BTN', isoCode: 'BT', displayNameEn: 'Bhutan', displayNameSr: 'Butan' },
            { mcc: 'BOL', isoCode: 'BO', displayNameEn: 'Bolivia', displayNameSr: 'Bolivija' },
            { mcc: 'BES', isoCode: 'BQ', displayNameEn: 'Bonaire', displayNameSr: 'Bonaire' },
            { mcc: 'BIH', isoCode: 'BA', displayNameEn: 'Bosnia & Herzegovina', displayNameSr: 'Bosna i Hercegovina' },
            { mcc: 'BWA', isoCode: 'BW', displayNameEn: 'Botswana', displayNameSr: 'Bocvana' },
            { mcc: 'BRA', isoCode: 'BR', displayNameEn: 'Brazil', displayNameSr: 'Brazil' },
            { mcc: 'VGB', isoCode: 'VG', displayNameEn: 'British Virgin Islands', displayNameSr: 'Britanska Djevičanska Ostrva' },
            { mcc: 'BRN', isoCode: 'BN', displayNameEn: 'Brunei', displayNameSr: 'Brunej' },
            { mcc: 'BGR', isoCode: 'BG', displayNameEn: 'Bulgaria', displayNameSr: 'Bugarska' },
            { mcc: 'BFA', isoCode: 'BF', displayNameEn: 'Burkina Faso', displayNameSr: 'Burkina Faso' },
            { mcc: 'BDI', isoCode: 'BI', displayNameEn: 'Burundi', displayNameSr: 'Burundi' },
            { mcc: 'KHM', isoCode: 'KH', displayNameEn: 'Cambodia', displayNameSr: 'Kambodža' },
            { mcc: 'CMR', isoCode: 'CM', displayNameEn: 'Cameroon', displayNameSr: 'Kamerun' },
            { mcc: 'CAN', isoCode: 'CA', displayNameEn: 'Canada', displayNameSr: 'Kanada' },
            { mcc: 'CPV', isoCode: 'CV', displayNameEn: 'Cape Verde', displayNameSr: 'Zelenortska Ostrva' },
            { mcc: 'CYM', isoCode: 'KY', displayNameEn: 'Cayman Islands', displayNameSr: 'Kajmanska Ostrva' },
            { mcc: 'CAF', isoCode: 'CF', displayNameEn: 'Central African Republic', displayNameSr: 'Centralnoafrička Republika' },
            { mcc: 'TCD', isoCode: 'TD', displayNameEn: 'Chad', displayNameSr: 'Čad' },
            { mcc: 'CHL', isoCode: 'CL', displayNameEn: 'Chile', displayNameSr: 'Čile' },
            { mcc: 'CHN', isoCode: 'CN', displayNameEn: 'China', displayNameSr: 'Kina' },
            { mcc: 'COL', isoCode: 'CO', displayNameEn: 'Colombia', displayNameSr: 'Kolumbija' },
            { mcc: 'COD', isoCode: 'CD', displayNameEn: 'Congo (DRC)', displayNameSr: 'Kongo (DRK)' },
            { mcc: 'COG', isoCode: 'CG', displayNameEn: 'Congo (Republic)', displayNameSr: 'Kongo (Republika)' },
            { mcc: 'CRI', isoCode: 'CR', displayNameEn: 'Costa Rica', displayNameSr: 'Kostarika' },
            { mcc: 'CIV', isoCode: 'CI', displayNameEn: 'Cote d’Ivoire', displayNameSr: 'Obala Slonovače' },
            { mcc: 'HRV', isoCode: 'HR', displayNameEn: 'Croatia', displayNameSr: 'Hrvatska' },
            { mcc: 'CUB', isoCode: 'CU', displayNameEn: 'Cuba', displayNameSr: 'Kuba' },
            { mcc: 'CUW', isoCode: 'CW', displayNameEn: 'Curacao', displayNameSr: 'Kurasao' },
            { mcc: 'CYP', isoCode: 'CY', displayNameEn: 'Cyprus', displayNameSr: 'Kipar' },
            { mcc: 'CZE', isoCode: 'CZ', displayNameEn: 'Czech Republic', displayNameSr: 'Češka' },
            { mcc: 'DNK', isoCode: 'DK', displayNameEn: 'Denmark', displayNameSr: 'Danska' },
            { mcc: 'DMA', isoCode: 'DM', displayNameEn: 'Dominica', displayNameSr: 'Dominika' },
            { mcc: 'DOM', isoCode: 'DO', displayNameEn: 'Dominican Republic', displayNameSr: 'Dominikanska Republika' },
            { mcc: 'ECU', isoCode: 'EC', displayNameEn: 'Ecuador', displayNameSr: 'Ekvador' },
            { mcc: 'EGY', isoCode: 'EG', displayNameEn: 'Egypt', displayNameSr: 'Egipat' },
            { mcc: 'SLV', isoCode: 'SV', displayNameEn: 'El Salvador', displayNameSr: 'Salvador' },
            { mcc: 'GNQ', isoCode: 'GQ', displayNameEn: 'Equatorial Guinea', displayNameSr: 'Ekvatorijalna Gvineja' },
            { mcc: 'EST', isoCode: 'EE', displayNameEn: 'Estonia', displayNameSr: 'Estonija' },
            { mcc: 'SWZ', isoCode: 'SZ', displayNameEn: 'Eswatini', displayNameSr: 'Esvatini' },
            { mcc: 'ETH', isoCode: 'ET', displayNameEn: 'Ethiopia', displayNameSr: 'Etiopija' },
            { mcc: 'FRO', isoCode: 'FO', displayNameEn: 'Faroe Islands', displayNameSr: 'Farska Ostrva' },
            { mcc: 'FJI', isoCode: 'FJ', displayNameEn: 'Fiji', displayNameSr: 'Fidži' },
            { mcc: 'FIN', isoCode: 'FI', displayNameEn: 'Finland', displayNameSr: 'Finska' },
            { mcc: 'FRA', isoCode: 'FR', displayNameEn: 'France', displayNameSr: 'Francuska' },
            { mcc: 'GUF', isoCode: 'GF', displayNameEn: 'French Guiana', displayNameSr: 'Francuska Gvajana' },
            { mcc: 'PYF', isoCode: 'PF', displayNameEn: 'French Polynesia', displayNameSr: 'Francuska Polinezija' },
            { mcc: 'GAB', isoCode: 'GA', displayNameEn: 'Gabon', displayNameSr: 'Gabon' },
            { mcc: 'GMB', isoCode: 'GM', displayNameEn: 'Gambia', displayNameSr: 'Gambija' },
            { mcc: 'GEO', isoCode: 'GE', displayNameEn: 'Georgia', displayNameSr: 'Gruzija' },
            { mcc: 'DEU', isoCode: 'DE', displayNameEn: 'Germany', displayNameSr: 'Njemačka' },
            { mcc: 'GHA', isoCode: 'GH', displayNameEn: 'Ghana', displayNameSr: 'Gana' },
            { mcc: 'GIB', isoCode: 'GI', displayNameEn: 'Gibraltar', displayNameSr: 'Gibraltar' },
            { mcc: 'GRC', isoCode: 'GR', displayNameEn: 'Greece', displayNameSr: 'Grčka' },
            { mcc: 'GRL', isoCode: 'GL', displayNameEn: 'Greenland', displayNameSr: 'Grenland' },
            { mcc: 'GRD', isoCode: 'GD', displayNameEn: 'Grenada', displayNameSr: 'Grenada' },
            { mcc: 'GLP', isoCode: 'GP', displayNameEn: 'Guadeloupe', displayNameSr: 'Gvadalupa' },
            { mcc: 'GUM', isoCode: 'GU', displayNameEn: 'Guam', displayNameSr: 'Guam' },
            { mcc: 'GTM', isoCode: 'GT', displayNameEn: 'Guatemala', displayNameSr: 'Gvatemala' },
            { mcc: 'GGY', isoCode: 'GG', displayNameEn: 'Guernsey', displayNameSr: 'Gernzi' },
            { mcc: 'GIN', isoCode: 'GN', displayNameEn: 'Guinea', displayNameSr: 'Gvineja' },
            { mcc: 'GNB', isoCode: 'GW', displayNameEn: 'Guinea-Bissau', displayNameSr: 'Gvineja-Bisao' },
            { mcc: 'GUY', isoCode: 'GY', displayNameEn: 'Guyana', displayNameSr: 'Gajana' },
            { mcc: 'HTI', isoCode: 'HT', displayNameEn: 'Haiti', displayNameSr: 'Haiti' },
            { mcc: 'HND', isoCode: 'HN', displayNameEn: 'Honduras', displayNameSr: 'Honduras' },
            { mcc: 'HKG', isoCode: 'HK', displayNameEn: 'Hong Kong', displayNameSr: 'Hong Kong' },
            { mcc: 'HUN', isoCode: 'HU', displayNameEn: 'Hungary', displayNameSr: 'Mađarska' },
            { mcc: 'ISL', isoCode: 'IS', displayNameEn: 'Iceland', displayNameSr: 'Island' },
            { mcc: 'IND', isoCode: 'IN', displayNameEn: 'India', displayNameSr: 'Indija' },
            { mcc: 'IDN', isoCode: 'ID', displayNameEn: 'Indonesia', displayNameSr: 'Indonezija' },
            { mcc: 'IRQ', isoCode: 'IQ', displayNameEn: 'Iraq', displayNameSr: 'Irak' },
            { mcc: 'IRL', isoCode: 'IE', displayNameEn: 'Ireland', displayNameSr: 'Irska' },
            { mcc: 'IMN', isoCode: 'IM', displayNameEn: 'Isle of Man', displayNameSr: 'Ostrvo Man' },
            { mcc: 'ISR', isoCode: 'IL', displayNameEn: 'Israel', displayNameSr: 'Izrael' },
            { mcc: 'ITA', isoCode: 'IT', displayNameEn: 'Italy', displayNameSr: 'Italija' },
            { mcc: 'JAM', isoCode: 'JM', displayNameEn: 'Jamaica', displayNameSr: 'Jamajka' },
            { mcc: 'JPN', isoCode: 'JP', displayNameEn: 'Japan', displayNameSr: 'Japan' },
            { mcc: 'JEY', isoCode: 'JE', displayNameEn: 'Jersey', displayNameSr: 'Džersi' },
            { mcc: 'JOR', isoCode: 'JO', displayNameEn: 'Jordan', displayNameSr: 'Jordan' },
            { mcc: 'KAZ', isoCode: 'KZ', displayNameEn: 'Kazakhstan', displayNameSr: 'Kazahstan' },
            { mcc: 'KEN', isoCode: 'KE', displayNameEn: 'Kenya', displayNameSr: 'Kenija' },
            { mcc: 'KOR', isoCode: 'KR', displayNameEn: 'Korea, Republic of', displayNameSr: 'Južna Koreja' },
            { mcc: 'XKX', isoCode: 'XK', displayNameEn: 'Kosovo', displayNameSr: 'Kosovo' },
            { mcc: 'KWT', isoCode: 'KW', displayNameEn: 'Kuwait', displayNameSr: 'Kuvajt' },
            { mcc: 'KGZ', isoCode: 'KG', displayNameEn: 'Kyrgyzstan', displayNameSr: 'Kirgistan' },
            { mcc: 'LAO', isoCode: 'LA', displayNameEn: 'Laos', displayNameSr: 'Laos' },
            { mcc: 'LVA', isoCode: 'LV', displayNameEn: 'Latvia', displayNameSr: 'Letonija' },
            { mcc: 'LBN', isoCode: 'LB', displayNameEn: 'Lebanon', displayNameSr: 'Liban' },
            { mcc: 'LSO', isoCode: 'LS', displayNameEn: 'Lesotho', displayNameSr: 'Lesoto' },
            { mcc: 'LBR', isoCode: 'LR', displayNameEn: 'Liberia', displayNameSr: 'Liberija' },
            { mcc: 'LBY', isoCode: 'LY', displayNameEn: 'Libya', displayNameSr: 'Libija' },
            { mcc: 'LIE', isoCode: 'LI', displayNameEn: 'Liechtenstein', displayNameSr: 'Lihtenštajn' },
            { mcc: 'LTU', isoCode: 'LT', displayNameEn: 'Lithuania', displayNameSr: 'Litvanija' },
            { mcc: 'LUX', isoCode: 'LU', displayNameEn: 'Luxembourg', displayNameSr: 'Luksemburg' },
            { mcc: 'MAC', isoCode: 'MO', displayNameEn: 'Macau', displayNameSr: 'Makao' },
            { mcc: 'MKD', isoCode: 'MK', displayNameEn: 'Macedonia', displayNameSr: 'Severna Makedonija' },
            { mcc: 'MDG', isoCode: 'MG', displayNameEn: 'Madagascar', displayNameSr: 'Madagaskar' },
            { mcc: 'MWI', isoCode: 'MW', displayNameEn: 'Malawi', displayNameSr: 'Malavi' },
            { mcc: 'MYS', isoCode: 'MY', displayNameEn: 'Malaysia', displayNameSr: 'Malezija' },
            { mcc: 'MDV', isoCode: 'MV', displayNameEn: 'Maldives', displayNameSr: 'Maldivi' },
            { mcc: 'MLI', isoCode: 'ML', displayNameEn: 'Mali', displayNameSr: 'Mali' },
            { mcc: 'MLT', isoCode: 'MT', displayNameEn: 'Malta', displayNameSr: 'Malta' },
            { mcc: 'MTQ', isoCode: 'MQ', displayNameEn: 'Martinique', displayNameSr: 'Martinik' },
            { mcc: 'MRT', isoCode: 'MR', displayNameEn: 'Mauritania', displayNameSr: 'Mauritanija' },
            { mcc: 'MUS', isoCode: 'MU', displayNameEn: 'Mauritius', displayNameSr: 'Mauricijus' },
            { mcc: 'MYT', isoCode: 'YT', displayNameEn: 'Mayotte', displayNameSr: 'Majot' },
            { mcc: 'MEX', isoCode: 'MX', displayNameEn: 'Mexico', displayNameSr: 'Meksiko' },
            { mcc: 'MDA', isoCode: 'MD', displayNameEn: 'Moldova', displayNameSr: 'Moldavija' },
            { mcc: 'MCO', isoCode: 'MC', displayNameEn: 'Monaco', displayNameSr: 'Monako' },
            { mcc: 'MNG', isoCode: 'MN', displayNameEn: 'Mongolia', displayNameSr: 'Mongolija' },
            { mcc: 'MNE', isoCode: 'ME', displayNameEn: 'Montenegro', displayNameSr: 'Crna Gora' },
            { mcc: 'MSR', isoCode: 'MS', displayNameEn: 'Montserrat', displayNameSr: 'Monserat' },
            { mcc: 'MAR', isoCode: 'MA', displayNameEn: 'Morocco', displayNameSr: 'Maroko' },
            { mcc: 'MOZ', isoCode: 'MZ', displayNameEn: 'Mozambique', displayNameSr: 'Mozambik' },
            { mcc: 'MMR', isoCode: 'MM', displayNameEn: 'Myanmar', displayNameSr: 'Mjanmar' },
            { mcc: 'NAM', isoCode: 'NA', displayNameEn: 'Namibia', displayNameSr: 'Namibija' },
            { mcc: 'NRU', isoCode: 'NR', displayNameEn: 'Nauru', displayNameSr: 'Nauru' },
            { mcc: 'NPL', isoCode: 'NP', displayNameEn: 'Nepal', displayNameSr: 'Nepal' },
            { mcc: 'NLD', isoCode: 'NL', displayNameEn: 'Netherlands', displayNameSr: 'Holandija' },
            { mcc: 'ANT', isoCode: 'NA', displayNameEn: 'Netherlands Antilles', displayNameSr: 'Holandski Antili' },
            { mcc: 'NCL', isoCode: 'NC', displayNameEn: 'New Caledonia', displayNameSr: 'Nova Kaledonija' },
            { mcc: 'NZL', isoCode: 'NZ', displayNameEn: 'New Zealand', displayNameSr: 'Novi Zeland' },
            { mcc: 'NIC', isoCode: 'NI', displayNameEn: 'Nicaragua', displayNameSr: 'Nikaragva' },
            { mcc: 'NER', isoCode: 'NE', displayNameEn: 'Niger', displayNameSr: 'Niger' },
            { mcc: 'NGA', isoCode: 'NG', displayNameEn: 'Nigeria', displayNameSr: 'Nigerija' },
            { mcc: 'MNP', isoCode: 'AN', displayNameEn: 'Northern Mariana Islands', displayNameSr: 'Severna Marijanska Ostrva' },
            { mcc: 'NOR', isoCode: 'NO', displayNameEn: 'Norway', displayNameSr: 'Norveška' },
            { mcc: 'OMN', isoCode: 'OM', displayNameEn: 'Oman', displayNameSr: 'Oman' },
            { mcc: 'PAK', isoCode: 'PK', displayNameEn: 'Pakistan', displayNameSr: 'Pakistan' },
            { mcc: 'PSE', isoCode: 'PS', displayNameEn: 'Palestine', displayNameSr: 'Palestina' },
            { mcc: 'PAN', isoCode: 'PA', displayNameEn: 'Panama', displayNameSr: 'Panama' },
            { mcc: 'PNG', isoCode: 'PG', displayNameEn: 'Papua New Guinea', displayNameSr: 'Papua Nova Gvineja' },
            { mcc: 'PRY', isoCode: 'PY', displayNameEn: 'Paraguay', displayNameSr: 'Paragvaj' },
            { mcc: 'PER', isoCode: 'PE', displayNameEn: 'Peru', displayNameSr: 'Peru' },
            { mcc: 'PHL', isoCode: 'PH', displayNameEn: 'Philippines', displayNameSr: 'Filipini' },
            { mcc: 'POL', isoCode: 'PL', displayNameEn: 'Poland', displayNameSr: 'Poljska' },
            { mcc: 'PRT', isoCode: 'PT', displayNameEn: 'Portugal', displayNameSr: 'Portugalija' },
            { mcc: 'PRI', isoCode: 'PR', displayNameEn: 'Puerto Rico', displayNameSr: 'Portoriko' },
            { mcc: 'QAT', isoCode: 'QA', displayNameEn: 'Qatar', displayNameSr: 'Katar' },
            { mcc: 'REU', isoCode: 'RE', displayNameEn: 'Reunion', displayNameSr: 'Reunion' },
            { mcc: 'ROM', isoCode: 'RO', displayNameEn: 'Romania', displayNameSr: 'Rumunija' },
            { mcc: 'RUS', isoCode: 'RU', displayNameEn: 'Russia', displayNameSr: 'Rusija' },
            { mcc: 'RWA', isoCode: 'RW', displayNameEn: 'Rwanda', displayNameSr: 'Ruanda' },
            { mcc: 'BLM', isoCode: 'BL', displayNameEn: 'Saint Barthelemy', displayNameSr: 'Sveti Bartolomej' },
            { mcc: 'MAF', isoCode: 'MF', displayNameEn: 'Saint Martin (French Part)', displayNameSr: 'Sveti Martin' },
            { mcc: 'WSM', isoCode: 'WS', displayNameEn: 'Samoa', displayNameSr: 'Samoa' },
            { mcc: 'ITA', isoCode: 'IT', displayNameEn: 'San Marino', displayNameSr: 'San Marino' },
            { mcc: 'STP', isoCode: 'ST', displayNameEn: 'Sao Tome and Principe', displayNameSr: 'Sao Tome i Principe' },
            { mcc: 'SAU', isoCode: 'SA', displayNameEn: 'Saudi Arabia', displayNameSr: 'Saudijska Arabija' },
            { mcc: 'SEN', isoCode: 'SN', displayNameEn: 'Senegal', displayNameSr: 'Senegal' },
            { mcc: 'SRB', isoCode: 'RS', displayNameEn: 'Serbia', displayNameSr: 'Srbija' },
            { mcc: 'SYC', isoCode: 'SC', displayNameEn: 'Seychelles', displayNameSr: 'Sejšeli' },
            { mcc: 'SLE', isoCode: 'SL', displayNameEn: 'Sierra Leone', displayNameSr: 'Sijera Leone' },
            { mcc: 'SGP', isoCode: 'SG', displayNameEn: 'Singapore', displayNameSr: 'Singapur' },
            { mcc: 'SXM', isoCode: 'SX', displayNameEn: 'Sint Maarten', displayNameSr: 'Sint Marten' },
            { mcc: 'SVK', isoCode: 'SK', displayNameEn: 'Slovakia', displayNameSr: 'Slovačka' },
            { mcc: 'SVN', isoCode: 'SI', displayNameEn: 'Slovenia', displayNameSr: 'Slovenija' },
            { mcc: 'SLB', isoCode: 'SB', displayNameEn: 'Solomon Islands', displayNameSr: 'Solomonska Ostrva' },
            { mcc: 'ZAF', isoCode: 'ZA', displayNameEn: 'South Africa', displayNameSr: 'Južnoafrička Republika' },
            { mcc: 'SSD', isoCode: 'SS', displayNameEn: 'South Sudan', displayNameSr: 'Južni Sudan' },
            { mcc: 'ESP', isoCode: 'ES', displayNameEn: 'Spain', displayNameSr: 'Španija' },
            { mcc: 'LKA', isoCode: 'LK', displayNameEn: 'Sri Lanka', displayNameSr: 'Šri Lanka' },
            { mcc: 'KNA', isoCode: 'KN', displayNameEn: 'St Kitts & Nevis', displayNameSr: 'Sent Kits i Nevis' },
            { mcc: 'LCA', isoCode: 'LC', displayNameEn: 'St Lucia', displayNameSr: 'Sent Lucija' },
            { mcc: 'VCT', isoCode: 'VC', displayNameEn: 'St Vincent & the Grenadines', displayNameSr: 'Sent Vinsent i Grenadini' },
            { mcc: 'SDN', isoCode: 'SD', displayNameEn: 'Sudan', displayNameSr: 'Sudan' },
            { mcc: 'SUR', isoCode: 'SR', displayNameEn: 'Suriname', displayNameSr: 'Surinam' },
            { mcc: 'SZW', isoCode: 'SZ', displayNameEn: 'Swaziland', displayNameSr: 'Svazilend' },
            { mcc: 'SWE', isoCode: 'SE', displayNameEn: 'Sweden', displayNameSr: 'Švedska' },
            { mcc: 'CHE', isoCode: 'CH', displayNameEn: 'Switzerland', displayNameSr: 'Švajcarska' },
            { mcc: 'TWN', isoCode: 'TW', displayNameEn: 'Taiwan', displayNameSr: 'Tajvan' },
            { mcc: 'TJK', isoCode: 'TJ', displayNameEn: 'Tajikistan', displayNameSr: 'Tadžikistan' },
            { mcc: 'TZA', isoCode: 'TZ', displayNameEn: 'Tanzania', displayNameSr: 'Tanzanija' },
            { mcc: 'THA', isoCode: 'TH', displayNameEn: 'Thailand', displayNameSr: 'Tajland' },
            { mcc: 'TLS', isoCode: 'TL', displayNameEn: 'Timor L\'este', displayNameSr: 'Timor-Leste' },
            { mcc: 'TGO', isoCode: 'TG', displayNameEn: 'Togo', displayNameSr: 'Togo' },
            { mcc: 'TON', isoCode: 'TO', displayNameEn: 'Tonga', displayNameSr: 'Tonga' },
            { mcc: 'TTO', isoCode: 'TT', displayNameEn: 'Trinidad & Tobago', displayNameSr: 'Trinidad i Tobago' },
            { mcc: 'TUN', isoCode: 'TN', displayNameEn: 'Tunisia', displayNameSr: 'Tunis' },
            { mcc: 'TUR', isoCode: 'TR', displayNameEn: 'Turkey', displayNameSr: 'Turska' },
            { mcc: 'TCA', isoCode: 'TC', displayNameEn: 'Turks & Caicos Islands', displayNameSr: 'Ostrva Turks i Kaikos' },
            { mcc: 'UGA', isoCode: 'UG', displayNameEn: 'Uganda', displayNameSr: 'Uganda' },
            { mcc: 'UKR', isoCode: 'UA', displayNameEn: 'Ukraine', displayNameSr: 'Ukrajina' },
            { mcc: 'ARE', isoCode: 'AE', displayNameEn: 'United Arab Emirates', displayNameSr: 'Ujedinjeni Arapski Emirati' },
            { mcc: 'GBR', isoCode: 'GB', displayNameEn: 'United Kingdom', displayNameSr: 'Ujedinjeno Kraljevstvo' },
            { mcc: 'USA', isoCode: 'US', displayNameEn: 'United States', displayNameSr: 'Sjedinjene Američke Države' },
            { mcc: 'VIR', isoCode: 'VI', displayNameEn: 'United States Virgin Islands', displayNameSr: 'Američka Djevičanska Ostrva' },
            { mcc: 'URY', isoCode: 'UY', displayNameEn: 'Uruguay', displayNameSr: 'Urugvaj' },
            { mcc: 'UZB', isoCode: 'UZ', displayNameEn: 'Uzbekistan', displayNameSr: 'Uzbekistan' },
            { mcc: 'VUT', isoCode: 'VU', displayNameEn: 'Vanuatu', displayNameSr: 'Vanuatu' },
            { mcc: 'VEN', isoCode: 'VE', displayNameEn: 'Venezuela', displayNameSr: 'Venecuela' },
            { mcc: 'VNM', isoCode: 'VN', displayNameEn: 'Vietnam', displayNameSr: 'Vijetnam' },
            { mcc: 'YEM', isoCode: 'YE', displayNameEn: 'Yemen', displayNameSr: 'Jemen' },
            { mcc: 'ZMB', isoCode: 'ZM', displayNameEn: 'Zambia', displayNameSr: 'Zambija' },
            { mcc: 'ZWE', isoCode: 'ZW', displayNameEn: 'Zimbabwe', displayNameSr: 'Zimbabve' }
        ],
    });


    await prisma.region.createMany({
        data: [
            {
                displayNameEn: "Asia",
                displayNameSr: "Azija",
                code: "Asia",
                keywords: "Asia",
            },
            {
                displayNameEn: "Balkans",
                displayNameSr: "Balkan",
                code: "Balkans",
                keywords: "Balkans",
            },
            {
                displayNameEn: "Caribbean",
                displayNameSr: "Karibi",
                code: "Caribbean",
                keywords: "Caribbean",
            },
            {
                displayNameEn: "Europe",
                displayNameSr: "Evropa",
                code: "Europe",
                keywords: "Europe",
            },
            {
                displayNameEn: "Latin America",
                displayNameSr: "Latinska Amerika",
                code: "Latin America",
                keywords: "Latin America",
            },
            {
                displayNameEn: "Middle East",
                displayNameSr: "Bliski istok",
                code: "Middle East",
                keywords: "Middle East",
            },
            {
                displayNameEn: "North America",
                displayNameSr: "Severna Amerika",
                code: "North America",
                keywords: "North America",
            },
            {
                displayNameEn: "SEA-Oceania",
                displayNameSr: "Jugoistočna Azija i Okeanija",
                code: "SEA-Oceania",
                keywords: "SEA-Oceania",
            },
        ],
    });


    // await prisma.product.createMany({
    //     data: [
    //         { name: "1gb 7 day", duration: 7, durationUnit: "days", amount: 1, amountUnit: "GB", basePrice: 1.25, countryId: 28 },
    //         { name: "2gb 14 day", duration: 14, durationUnit: "days", amount: 2, amountUnit: "GB", basePrice: 2.5, countryId: 28 },
    //         { name: "3gb 21 day", duration: 21, durationUnit: "days", amount: 3, amountUnit: "GB", basePrice: 3.75, countryId: 28 },
    //         { name: "5gb 30 day", duration: 30, durationUnit: "days", amount: 5, amountUnit: "GB", basePrice: 5.00, countryId: 28 },
    //         { name: "1gb 7 day", duration: 7, durationUnit: "days", amount: 1, amountUnit: "GB", basePrice: 1.25, countryId: 27 },
    //         { name: "2gb 14 day", duration: 14, durationUnit: "days", amount: 2, amountUnit: "GB", basePrice: 2.50, countryId: 27 },
    //         { name: "3gb 21 day", duration: 21, durationUnit: "days", amount: 5, amountUnit: "GB", basePrice: 3.75, countryId: 27 },
    // { name: "1gb 7 day", duration: 7, durationUnit: "days", amount: 1, amountUnit: "GB", basePrice: 5, regionId: 50 },
    // { name: "2gb 14 day", duration: 14, durationUnit: "days", amount: 2, amountUnit: "GB", basePrice: 10, regionId: 50 },
    // { name: "3gb 21 day", duration: 21, durationUnit: "days", amount: 5, amountUnit: "GB", basePrice: 15, regionId: 50 },

    // ],
    // });

    // await prisma.couponCode.createMany({
    //     data: [
    //         { code: "all", countryPercentage: 10, regionPercentage: 10, subjectEmail: "tropic@example.com", subjectName: "All", couponType: "All" },
    //         { code: "country10", countryPercentage: 10, regionPercentage: null, subjectEmail: "tropic@example.com", subjectName: "Only country", couponType: "OnlyCountry" },
    //         { code: "countryWithout10", countryPercentage: 10, regionPercentage: null, subjectEmail: "tropic@example.com", subjectName: "Only country without discount", couponType: "OnlyCountryWithoutDiscount" },
    //         { code: "custom", countryPercentage: 20, regionPercentage: 10, subjectEmail: "tropic@example.com", subjectName: "Custom", couponType: "CustomPercentageCountryRegion" },
    //         { code: "free", subjectEmail: "tropic@example.com", subjectName: "Free", couponType: "Free" },

    //     ],
    // });
}

main()
    .then(() => {
        console.log('Database seeded successfully!')
    })
    .catch((e) => {
        console.error(e)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })